roskakori/pygount

pygount/command.py
tests/test_command.py

Ouptuts summary by source type.
Signed-off-by: Yuriy Petrovskiy <yuriy.petrovskiy@gmail.com>

Implemented --summary parameter

---

README.rst
pygount/write.py
tests/test_write.py

* Fixed code count for some total.
* Added separators to output.

#16 Improved summary

---

README.md

#38 Fixed workflow name.

---

CHANGES.md
CONTRIBUTING.md
pygount/__init__.py
pygount/analysis.py
pygount/summary.py
pygount/write.py
tests/test_analysis.py
tests/test_summary.py
tests/test_write.py

#37 Added file count to summary

---

docs/api.rst
docs/changes.rst
docs/contributing.rst
pygount/analysis.py
pygount/summary.py
pygount/write.py
setup.cfg
tests/test_analysis.py
tests/test_summary.py

* Changed attributes in `SourceAnalysis` to read-only properties.
* Renamed properties holding counts from `xxx` to `xxx_count`.

#44 Cleaned up API and API documentation.

---

README.md

#44 Fixed broken links and upgraded others to HTTPS.

---

dev-requirements.txt
docs/changes.rst
docs/requirements.txt
pygount/analysis.py
pygount/common.py
setup.py
tests/test_analysis.py

#53 Improve text file detection

---

dev-requirements.txt
docs/changes.rst
docs/requirements.txt
pygount/analysis.py
pygount/common.py
tests/test_analysis.py

#56 Fixed scanning of "." (current folder)

---

.github/workflows/build.yml
LICENSE.txt
README.md
docs/conf.py
pygount/__init__.py
pygount/analysis.py
pygount/command.py
pygount/common.py
pygount/lexers.py
pygount/summary.py
pygount/write.py
pygount/xmldialect.py
setup.py
tests/test_analysis.py
tests/test_command.py
tests/test_common.py
tests/test_lexers.py
tests/test_write.py
tests/test_xmldialect.py

Fix minor issues 3.9

---

.github/workflows/build.yml
.pre-commit-config.yaml
dev-requirements.txt
docs/changes.rst
pygount/analysis.py
pygount/write.py
scripts/update_dependencies.sh
setup.py
tests/test_analysis.py
tests/test_write.py

#64 Updated dependencies.

---

.pre-commit-config.yaml

#64 Changed black repository to official one

---

.pre-commit-config.yaml

#64 Updated deprecated check.

---

.pre-commit-config.yaml
pygount/__init__.py
pygount/command.py
pygount/common.py
pygount/summary.py
pygount/xmldialect.py
setup.cfg
setup.py
tests/_common.py
tests/test_analysis.py
tests/test_command.py
tests/test_write.py

#68 Improve pre commit checks

---

README.md

#75 Changed build status badge

---

.github/workflows/build.yml

#75 Fixed syntax error.

---

.github/workflows/build.yml
LICENSE.txt
docs/conf.py
poetry.lock
pygount/__init__.py
pygount/analysis.py
pygount/command.py
pygount/common.py
pygount/lexers.py
pygount/summary.py
pygount/write.py
pygount/xmldialect.py
pyproject.toml
tests/test_analysis.py
tests/test_command.py
tests/test_common.py
tests/test_lexers.py
tests/test_write.py
tests/test_xmldialect.py

#75 Updated copyright year and supported Python versions.

---

.gitignore
.idea/.gitignore
.idea/encodings.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
.idea/modules.xml
.idea/pygount.iml
.idea/vcs.xml

#75 Added PyCharm settings.

---

.github/workflows/build.yml
.idea/pygount.iml

#75 Documented failed experiment to improved parallelization of build.

---

tests/_common.py
tests/test_summary.py

#75 Added copyright comment.

---

docs/background.rst
docs/changes.rst
docs/index.rst
docs/json.rst
docs/usage.rst
pygount/analysis.py
pygount/command.py
pygount/summary.py
pygount/write.py
tests/test_command.py

#62 Added JSON as additional output --format.

---

docs/changes.rst
pygount/write.py
tests/test_write.py

#62 Fixed computation of runtime statistic "lines per second".

---

docs/changes.rst
pygount/analysis.py

#54 Added detection of GitHub community files without suffix as text.

---

README.md
docs/changes.rst
docs/contributing.rst

#75 Added release cheatsheet.

---

LICENSE.txt
docs/conf.py
pygount/__init__.py
pygount/analysis.py
pygount/command.py
pygount/common.py
pygount/lexers.py
pygount/summary.py
pygount/write.py
pygount/xmldialect.py
tests/_common.py
tests/test_analysis.py
tests/test_command.py
tests/test_common.py
tests/test_lexers.py
tests/test_summary.py
tests/test_write.py
tests/test_xmldialect.py

#97 Update copyright year to 2023

---

.gitattributes
docs/changes.rst
pygount/command.py
pygount/common.py
pygount/write.py
pyproject.toml

#91 Fix missing output on Windows with --format=sloccount

---

pygount/analysis.py
tests/test_analysis.py

This implements the feature requested in #100.

Allow analyzing code from an open file

---

docs/changes.rst

#114 Bump release date

---

.github/workflows/build.yml
.idea/misc.xml
docs/changes.rst
docs/usage.rst
pygount/analysis.py
pygount/command.py
tests/test_analysis.py
tests/test_command.py

#105 Add option to merge embedded languages

---

pygount/write.py

#105 Clean up deprecation warnings

---

docs/changes.rst

- See #137 
We simply forgot to add this to the changelog.

#137 Add missing change description

---

LICENSE.txt
docs/conf.py
pygount/__init__.py
pygount/analysis.py
pygount/command.py
pygount/common.py
pygount/lexers.py
pygount/summary.py
pygount/write.py
pygount/xmldialect.py
tests/_common.py
tests/test_analysis.py
tests/test_command.py
tests/test_common.py
tests/test_lexers.py
tests/test_summary.py
tests/test_write.py
tests/test_xmldialect.py

#149 Bump year to 2024

---

docs/background.rst
docs/changes.rst
docs/json.rst
pygount/analysis.py
pygount/summary.py
pygount/write.py
pyproject.toml
scripts/build_movie.sh

#122 Add code count to json output

---

.flake8
.pre-commit-config.yaml
docs/changes.rst
docs/conf.py
poetry.lock
pygount/analysis.py
pygount/command.py
pygount/common.py
pygount/git_storage.py
pygount/summary.py
pygount/write.py
pygount/xmldialect.py
pyproject.toml
tests/test_analysis.py
tests/test_command.py
tests/test_common.py
tests/test_lexers.py
tests/test_write.py

#157 Change linting to ruff

---

.pre-commit-config.yaml
README.md
docs/changes.rst
docs/json.rst

#160 Change default branch to main

---

pygount/analysis.py
pygount/git_storage.py
tests/test_analysis.py

#162 Fix silent error on git failing

---

docs/changes.rst
pygount/analysis.py
pygount/command.py
pygount/common.py
pygount/git_storage.py
pygount/summary.py
pyproject.toml
tests/_common.py
tests/test_analysis.py
tests/test_write.py
uv.lock

#158 Remove support for Python 3.8

---

.github/workflows/build.yml
docs/changes.rst
pyproject.toml

#174 Add Python 3.13

---

.github/workflows/build.yml
.gitignore
.pre-commit-config.yaml
docs/changes.rst
pygount/lexers.py
pyproject.toml
scripts/update_dependencies.sh
uv.lock

#194 Update dependencies

---

docs/changes.rst
pyproject.toml
scripts/update_dependencies.sh
uv.lock

#193 Change rich version handling

---

docs/contributing.rst

#164 Fix link

---

docs/api.md
docs/background.md
docs/changes.md
docs/continuous-integration.md
docs/contributing.md
docs/index.md
docs/json.md
docs/usage.md

- Close #191.
- Fix broken links caused by pandoc conversion from ReSTructured text
- Fix grammar and spelling
- Change paragraphs to consistently be a single long line
- Clean up version history:
- Each version is a Markdown heading
- Changes are consistently phrased in present tense

#191 Improve documentation
